# More options https://github.com/mochajs/mocha/blob/master/example/config/.mocharc.yml
ui: bdd
global: expect
require:
  - ts-node/register 
  - source-map-support/register
recursive: true
timeout: 5000
color: true
reporter: mocha-multi
reporter-option:
  - spec=-
  - mocha-junit-reporter=-
spec:
  - "**/src/**/*.test.ts"