name: netin-js$(Date:yyyyMMdd)$(Rev:.r)
trigger:
 - master
 - develop
 - release/*
 - hotfix/*
 - feature/*
pr:
 - master
 - develop

## Netin - Pipelines templates repository
resources:
  repositories:
    - repository: templates
      type: git
      name: NetinSystems/NS-DevOps-Pipelines
## Netin - General
variables:
  ## Artifact name
- name: artifactName
  value: 'NS-Netin-Crash-TypeScript'
- name: projectName
  value: NS-Netin-Crash-TypeScript
  ## Releases Wiki page
- name: artifactWikiFileName
  value: '@netin%2Djs-%2D-crash'
  ## GitFlow variables for branch maching
- template: templates/netin-pipelines-variables.yml@templates

stages:
  ## Stage CODE: GitVersion based on GitFlow, unit-tests and code analysis
  - stage: 'APP'
    displayName: 'Application Build'
    pool:
      name: NUCHUB
    jobs:
      - job: 'CODE_QUALITY'
        displayName: 'Code Quality Assurance'
        workspace:
          clean: all
        timeoutInMinutes: 15
        steps:
        - checkout: self
          clean: true
          persistCredentials: true
        - template: templates/netin-setup-gitversion.yml@templates
        - template: templates/netin-setup-node-and-yarn.yml@templates
          parameters:
            nodeVersion: '14.17.3'    
        - template: templates/netin-test-regular-repo.yml@templates
        - template: templates/netin-test-sonarqube-analysis.yml@templates
        - template: templates/netin-publish-artifacts-regular.yml@templates
          parameters:
            folder: ns-netin-crash
  - template: templates/stages/netin-release-library-version.yml@templates
    parameters:
      artifactName: ${{variables.artifactName}}
      artifactWikiFileName: ${{variables.artifactWikiFileName}}